/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import conexionSQL.conexionSQL;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SENA
 */
public class sistema extends javax.swing.JFrame {
    conexionSQL cc=new conexionSQL();
    Connection con=cc.conexion();

    /**
     * Creates new form sistema
     */
    public sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        genero = new javax.swing.JComboBox<>();
        cbTipodocumento = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAprendiz = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Nombre");

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de documento:");

        jLabel3.setText("Documento:");

        jLabel4.setText("Genero:");

        jLabel5.setText("Dirección:");

        jLabel6.setText("Celular:");

        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        cbTipodocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "CC", "Passaport" }));
        cbTipodocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipodocumentoActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRIVADO\\Documents\\NetBeansProjects\\crudFdsim\\crudFdsim\\build\\classes\\iconos-java\\icons8-nuevo-24.png")); // NOI18N
        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRIVADO\\Documents\\NetBeansProjects\\crudFdsim\\crudFdsim\\build\\classes\\iconos-java\\icons8-guardar-30.png")); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRIVADO\\Documents\\NetBeansProjects\\crudFdsim\\crudFdsim\\build\\classes\\iconos-java\\icons8-eliminar-propiedad-24.png")); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        actualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\PRIVADO\\Documents\\NetBeansProjects\\crudFdsim\\crudFdsim\\build\\classes\\iconos-java\\icons8-aprobar-y-actualizar-24.png")); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(celular)
                            .addComponent(direccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(actualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(documento)
                            .addComponent(nombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbTipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(actualizar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel7.setText("Buscar:");

        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        tablaAprendiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaAprendiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAprendizMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAprendiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscar)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCajas();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarRegistro(); 
        limpiarCajas();
        mostrarDatos();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        insertarDatos();
        limpiarCajas();
        mostrarDatos();
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbTipodocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipodocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipodocumentoActionPerformed

    private void tablaAprendizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAprendizMouseClicked
        int filaSeleccionada = tablaAprendiz.rowAtPoint(evt.getPoint());
        cbTipodocumento.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada, 0));
        documento.setText(tablaAprendiz.getValueAt(filaSeleccionada, 1).toString());
        nombre.setText(tablaAprendiz.getValueAt(filaSeleccionada, 2).toString());
        genero.setSelectedItem(tablaAprendiz.getValueAt(filaSeleccionada, 3));
        direccion.setText(tablaAprendiz.getValueAt(filaSeleccionada, 4).toString());
        celular.setText(tablaAprendiz.getValueAt(filaSeleccionada, 5).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tablaAprendizMouseClicked

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        actualizarDatos();
        limpiarCajas();
        mostrarDatos();        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        filtrarDatos(buscar.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyReleased
    public void insertarDatos(){
    try{
        String SQL="insert into datos(cbTipodocumento,documento,nombre,genero,direccion,celular) values (?,?,?,?,?,?)";
    
    java.sql.PreparedStatement pst=con.prepareStatement(SQL);
    int seleccionado=cbTipodocumento.getSelectedIndex();
    pst.setString(1, cbTipodocumento.getItemAt(seleccionado));
    
    pst.setDouble(2, Double.parseDouble(documento.getText()));
    pst.setString(3, nombre.getText());
    
    int seleccionado1=genero.getSelectedIndex();
    pst.setString(4, genero.getItemAt(seleccionado1));
    
    pst.setString(5, direccion.getText());
    pst.setDouble(6, Double.parseDouble(celular.getText()));
    
    pst.execute();
    JOptionPane.showMessageDialog(null, "Datos Registrados Correctamente");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error de registro"+e.getMessage());
    }
    }
    
    public void limpiarCajas() {
        cbTipodocumento.setSelectedItem(null);
        documento.setText(null);
        nombre.setText(null);
        genero.setSelectedItem(null);
        direccion.setText(null);
        celular.setText(null);

    }
    
    public void mostrarDatos() {
        String[] titulos = {"Tipo", "Documento", "Nombre", "Genero", "Direccion", "Telefono"};
        String[] registros = new String[7];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select* from datos";

        try {
            java.sql.Statement st = con.createStatement();
            var rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("cbTipodocumento");
                registros[1] = rs.getString("documento");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("genero");
                registros[4] = rs.getString("direccion");
                registros[5] = rs.getString("celular");
                modelo.addRow(registros);
            }
            tablaAprendiz.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de busqueda" + e.getMessage());
        }

    } 
    
    public void actualizarDatos(){
        try {
            String SQL = "update datos set cbTipodocumento=?,documento=?,nombre=?,genero=?,direccion=?,celular=? where documento=?";

            int filaSeleccionada = tablaAprendiz.getSelectedRow();
            String ref = (String) tablaAprendiz.getValueAt(filaSeleccionada, 1);

            java.sql.PreparedStatement pst = con.prepareStatement(SQL);
            int seleccionado = cbTipodocumento.getSelectedIndex();
            pst.setString(1, cbTipodocumento.getItemAt(seleccionado));

            pst.setDouble(2, Double.parseDouble(documento.getText()));
            pst.setString(3, nombre.getText());

            int seleccionado1 = genero.getSelectedIndex();
            pst.setString(4, genero.getItemAt(seleccionado1));

            pst.setString(5, direccion.getText());
            pst.setDouble(6, Double.parseDouble(celular.getText()));

            pst.setString(7, ref);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Datos Actualizados Correctamente");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Actualizacion" + e.getMessage());

        }
    }
    public void eliminarRegistro(){
            int filaSeleccionada=tablaAprendiz.getSelectedRow();
           
            try{
                String SQL="delete from datos where documento="+tablaAprendiz.getValueAt(filaSeleccionada,1);
                
                java.sql.Statement st=con.createStatement();
                int n=st.executeUpdate(SQL);
                
                if(n>=0){
                    JOptionPane.showMessageDialog(null,"Registro Eliminado");
                }
            } catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error al Eliminar Registro"+e.getMessage());
            }
        }
    public void filtrarDatos(String valor) {
        String[] titulos = {"Tipo", "Documento", "Nombre", "Genero", "Direccion", "Telefono"};
        String[] registros = new String[7];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        String SQL = "select* from datos where nombre like'%"+valor+"%'";
        

        try {
            java.sql.Statement st = con.createStatement();
            var rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("cbTipodocumento");
                registros[1] = rs.getString("documento");
                registros[2] = rs.getString("nombre");
                registros[3] = rs.getString("genero");
                registros[4] = rs.getString("direccion");
                registros[5] = rs.getString("celular");
                modelo.addRow(registros);
            }
            tablaAprendiz.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Registro" + e.getMessage());
        }
        
    }
        
    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JTextField buscar;
    private javax.swing.JComboBox<String> cbTipodocumento;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaAprendiz;
    // End of variables declaration//GEN-END:variables
}
