# Generated by Django 4.1 on 2022-09-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca'),
        ),
    ]
